version: '3.8'

services:
  backend:
    container_name: vhiobot-api
    build: .
    ports:
      - "8019:3009"
    restart: always
    env_file:
      - .env
    networks:
      - vhioshop

  redis:
    container_name: vhiobot-redis
    image: redis:7.4.1-alpine
    restart: always
    expose:
     - 6379
    volumes: 
      - redis-data:/data
    networks:
      - vhioshop

networks:
  vhioshop:
    external: true

volumes:
  redis-data:
    driver: local
